In [3]:
import numpy as np
from scipy.fft import fft

In [24]:
def fft_v(x):
    x = np.asarray(x, dtype=float)
    N = x.shape[0]
    if np.log2(N) % 1 > 0:
        raise ValueError("must be a power of 2")
        
    N_min = min(N, 2)
    
    n = np.arange(N_min)
    k = n[:, None]
    M = np.exp((-2j * np.pi * n * k/ N_min))
    X = np.dot(M, x.reshape((N_min, -1)))
    X_even = X[:, :int(X.shape[1] / 2)]
    X_odd = X[:, int(X.shape[1] / 2):]
    terms = np.exp(-1j * np.pi * np.arange(X.shape[0])
                        / X.shape[0])[:, None]
    X_N = np.vstack([X_even + terms * X_odd, X_even - terms * X_odd])
    return X_N
    '''
    while X.shape[0] < N:
        X_even = X[:, :int(X.shape[1] / 2)]
        X_odd = X[:, int(X.shape[1] / 2):]
        terms = np.exp(-1j * np.pi * np.arange(X.shape[0])
                        / X.shape[0])[:, None]
        X = np.vstack([X_even + terms * X_odd,
                       X_even - terms * X_odd])
    return X.ravel()'''

In [25]:
fft_v([1,2,3,4, 5, 6, 7, 8])

array([[16.+0.j, 20.+0.j],
       [-4.+4.j, -4.+4.j],
       [-4.+0.j, -4.+0.j],
       [-4.-4.j, -4.-4.j]])

In [11]:
fft_v([1,2,3,4, 5, 6, 7, 8])

array([[ 6.+0.00000000e+00j,  8.+0.00000000e+00j],
       [-4.-6.12323400e-16j, -4.-7.34788079e-16j]])

In [13]:
fft_v([1,2,3,4, 5, 6, 7, 8])

array([[1.000000e+00+0.j],
       [6.123234e-17-1.j]])

In [70]:
x = np.random.random(1024**2)

In [58]:
y = fft_v(x)

In [57]:
z = fft(x)

In [48]:
w = np.isclose(y, z)

In [49]:
all(w)

True

In [50]:
from cmath import exp, pi
 
def fft_e(x):
    N = len(x)
    if N <= 1: return x
    even = fft(x[0::2])
    odd =  fft(x[1::2])
    T= [exp(-2j*pi*k/N)*odd[k] for k in range(N//2)]
    return [even[k] + T[k] for k in range(N//2)] + \
           [even[k] - T[k] for k in range(N//2)]

In [52]:
j = fft_e(np.random.random(194688))

IndexError: list index out of range

In [42]:
all(np.isclose(z,j))

True